services:
  app:
    image: oxeee/theca-back:latest
    container_name: theca_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: goclean
      POSTGRES_PASSWORD: oxee
      POSTGRES_DB: gocleanarch
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
