definitions:
  domain.Bookmark:
    properties:
      icon_url:
        type: string
      id:
        type: integer
      show_text:
        type: boolean
      title:
        type: string
      url:
        type: string
      user_id:
        type: integer
    type: object
  pkg.ChangePassRequest:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  pkg.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  pkg.Response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  pkg.UserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  pkg.VerifyRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
info:
  contact: {}
paths:
  /api/bookmarks:
    get:
      consumes:
      - application/json
      description: Fetch all bookmarks associated with the current user
      produces:
      - application/json
      responses:
        "200":
          description: List of bookmarks
          schema:
            items:
              $ref: '#/definitions/domain.Bookmark'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Get bookmarks by user ID
      tags:
      - Bookmark
  /api/change-pass:
    post:
      description: Changes the user's password and deleting all sessions for this
        user
      parameters:
      - description: ChangePassRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/pkg.ChangePassRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Change user password
      tags:
      - User
  /api/create-bookmark:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bookmark
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.Bookmark'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Create a new user bookmark
      tags:
      - Bookmark
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and initiates a session by setting a session
        cookie.
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/pkg.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: User login
      tags:
      - User
  /api/logout:
    delete:
      description: Logout a user by deleting the session and removing the session
        cookie.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Logout a user
      tags:
      - User
  /bookmarks:
    delete:
      consumes:
      - application/json
      description: Delete a specific bookmark associated with the user based on the
        bookmark ID
      parameters:
      - description: Request body with the bookmark ID to delete
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Bookmark'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted the bookmark
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad request, invalid input
          schema:
            $ref: '#/definitions/pkg.Response'
        "403":
          description: Forbidden, the user does not have permission to delete this
            bookmark
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Delete a bookmark by ID
      tags:
      - Bookmark
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/pkg.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Register a new user
      tags:
      - User
  /verify-email:
    post:
      consumes:
      - application/json
      description: Verify email
      parameters:
      - description: VerifyRequest
        in: body
        name: verifyReq
        required: true
        schema:
          $ref: '#/definitions/pkg.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - CookieAuth: []
      summary: Verify email
      tags:
      - User
swagger: "2.0"
